### ISSUE TITLE
Autocomplete via schema.json

### ISSUE THREAD

**Issue by jhgg** [Gregoor/graphql-intellij-plugin#5]
Any plans to implement autocomplete like `graphiql` does it? By using a schema.json stored somewhere?

**Comment by Gregoor** [comment]
Would love to but I want to fix #2 and #3 first and I have to get some work on a different project done. I will look into in ~2-3 weeks.
Accepting pull requests though :+1:

**Comment by Gregoor** [comment]
3 weeks over and I didn't get to it. :/ I currently don't use that much GraphQL, so I can't really tell if and when this will be happening.

**Comment by Gregoor** [comment]
I stopped development, because there is a better GraphQL plugin now:
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

It supports autocomplete!
