### ISSUE TITLE
__typename is considered error

### ISSUE THREAD

**Issue by mwajeeh** [Gregoor/graphql-intellij-plugin#7]

**Comment by Gregoor** [comment]
thanks for filing the issue, I think it's the same issue as #6. Will fix it next time I get to work on this.

**Comment by Gregoor** [comment]
I stopped development, because there is a better GraphQL plugin now:
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

**Comment by mwajeeh** [comment]
Just FYI its not the same issue.
