### ISSUE TITLE
Remove the plugin from the JetBrains repository

### ISSUE THREAD

**Issue by jimkyndemeyer** [Gregoor/graphql-intellij-plugin#8]
Hey Gregoor.

I can see from the download stats that the plugin is still being downloaded from JetBrains.

Can you remove it from the JetBrains repository now that it's no longer being maintained? This will reduce the chance of confusion in end users. Existing users should have seen the "JS GraphQL" notification we discussed by now.

Thanks,
/Jim.

**Comment by Gregoor** [comment]
Hey Jim,

Sure thing, I just removed it. I wanted to keep it online for a while so everyone got the update with the message to switch to your version. I just hope that no one using a JetBrains product without JS support will be missing it.

Thanks for your great plugin,
Gregor

**Comment by jimkyndemeyer** [comment]
Thanks.

In case someone asks, there's an `android-studio` branch of the plugin which doesn't require the Node.js and JavaScript plugin: [js-graphql-intellij-plugin/tree/android-studio](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio). The .jar can be downloaded directly from that page.
